import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
      <nav className="flex justify-center items-center py-4 px-8">
  <ul className="flex-col space-y-4">
    <Link href="/calculator">
      <li className="list cursor-pointer hover:text-blue-500 border border-gray-300 p-4 mt-10 font-medium">Religious Calculator</li>
    </Link>
    <Link href="/zakat">
      <li className=" list cursor-pointer hover:text-blue-500 border border-gray-300 p-4 mt-10 font-medium">Zakat</li>
    </Link>
    <Link href="/usher">
      <li className=" list cursor-pointer hover:text-blue-500 border border-gray-300 p-4 mt-10 font-medium">Usher</li>
    </Link>
    <Link href="/miras">
      <li className=" list cursor-pointer hover:text-blue-500 border border-gray-300 p-4 mt-10 font-medium">Miras</li>
    </Link>
    <Link href="/fitrana">
      <li className=" list cursor-pointer hover:text-blue-500 border border-gray-300 p-4 mt-10 font-medium">Fitrana</li>
    </Link>
    <Link href="/fidia">
      <li className=" list cursor-pointer hover:text-blue-500 border border-gray-300 p-4 mt-10 font-medium">Fidia</li>
    </Link>
  </ul>
</nav>

      </main>
    </>
  )
}
